name: 'Shopify Theme JSON Syncs'
description: 'Sync Shopify Theme JSONs'
author: 'devil1991'
inputs:
  password:
    required: true
    description: 'Theme Sectet / Password'

  store:
    required: true
    description: 'Store'

  theme:
    required: true
    description: 'Target Theme ID'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler: 'latest'

    - name: Install Shopify CLI
      shell: bash
      run: npm install -g @shopify/cli @shopify/theme

    - name: Sync Theme
      run: dist/index.js
      shell: bash
