name: 'Shopify Theme JSON Syncs'
description: 'Sync Shopify Theme JSONs'
author: 'devil1991'
inputs:
  store:
    required: true
    description: 'Store'

  theme:
    required: true
    description: 'Target Theme ID'

  working-directory:
    required: false
    description: 'Working Directory'
runs:
  main: 'dist/index.js'
  using: 'node20'
